spring:
  application:
    name: venkateswaramotors
  data:
    mongodb:
      uri: mongodb+srv://venkateshwaramotorstrl:yf59d2uLzzkiBrZK@cluster0.r741p.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: venkateswaramotors
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

# Email API Configuration
email:
  api:
    url: https://node-mailer-api-production-e8eb.up.railway.app
    endpoint: /send-email

# Server Configuration
server:
  port: 8888

# Logging Configuration
logging:
  level:
    com.monesh.venkateswaramotors: DEBUG
    org.springframework.security: DEBUG